steps:
  - label: 'test command as installed from npm'
    command: |
      source ci/e2e_ci_prepare_env.sh
      source ci/e2e_ci_prepare_log.sh
      node ci/patch_contract_version.js
      ci/test_npm_package.sh

    artifact_paths:
      - 'logs/**/*.log'

    timeout: 40

    agents:
      - 'queue=default'
